import type {
  BadgePalette,
  TechnologyBadgePreset,
} from './badgeTypes';

// Slugs and brand colors are pinned from the Simple Icons data published at
// https://unpkg.com/simple-icons@16.27.0/data/simple-icons.json.
// Java, AWS, and Visual Studio Code were removed from current releases; their
// metadata is pinned from 4.25.0 (Java) and 12.4.0 (AWS and VS Code).
// visionOS and SwiftUI have no dedicated entry, so they intentionally reuse
// the verified Apple and Swift metadata from 16.27.0.
export const technologyBadgePresets = [
  {
    id: 'swift',
    name: 'Swift',
    category: 'language',
    logoSlug: 'swift',
    brandColor: 'F05138',
    homepage: 'https://www.swift.org/',
    defaultLabel: 'language',
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    category: 'language',
    logoSlug: 'typescript',
    brandColor: '3178C6',
    homepage: 'https://www.typescriptlang.org/',
    defaultLabel: 'language',
  },
  {
    id: 'javascript',
    name: 'JavaScript',
    category: 'language',
    logoSlug: 'javascript',
    brandColor: 'F7DF1E',
    homepage: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/',
    defaultLabel: 'language',
  },
  {
    id: 'python',
    name: 'Python',
    category: 'language',
    logoSlug: 'python',
    brandColor: '3776AB',
    homepage: 'https://www.python.org/',
    defaultLabel: 'language',
  },
  {
    id: 'java',
    name: 'Java',
    category: 'language',
    logoSlug: 'java',
    brandColor: '007396',
    homepage: 'https://www.java.com/',
    defaultLabel: 'language',
  },
  {
    id: 'kotlin',
    name: 'Kotlin',
    category: 'language',
    logoSlug: 'kotlin',
    brandColor: '7F52FF',
    homepage: 'https://kotlinlang.org/',
    defaultLabel: 'language',
  },
  {
    id: 'c',
    name: 'C',
    category: 'language',
    logoSlug: 'c',
    brandColor: 'A8B9CC',
    homepage: 'https://www.open-std.org/jtc1/sc22/wg14/',
    defaultLabel: 'language',
  },
  {
    id: 'cpp',
    name: 'C++',
    category: 'language',
    logoSlug: 'cplusplus',
    brandColor: '00599C',
    homepage: 'https://isocpp.org/',
    defaultLabel: 'language',
  },
  {
    id: 'react',
    name: 'React',
    category: 'frontend',
    logoSlug: 'react',
    brandColor: '61DAFB',
    homepage: 'https://react.dev/',
    defaultLabel: 'frontend',
  },
  {
    id: 'vue',
    name: 'Vue.js',
    category: 'frontend',
    logoSlug: 'vuedotjs',
    brandColor: '4FC08D',
    homepage: 'https://vuejs.org/',
    defaultLabel: 'frontend',
  },
  {
    id: 'html5',
    name: 'HTML5',
    category: 'frontend',
    logoSlug: 'html5',
    brandColor: 'E34F26',
    homepage: 'https://html.spec.whatwg.org/',
    defaultLabel: 'frontend',
  },
  {
    id: 'css3',
    name: 'CSS3',
    category: 'frontend',
    logoSlug: 'css',
    brandColor: '663399',
    homepage: 'https://www.w3.org/Style/CSS/',
    defaultLabel: 'frontend',
  },
  {
    id: 'vite',
    name: 'Vite',
    category: 'frontend',
    logoSlug: 'vite',
    brandColor: '9135FF',
    homepage: 'https://vite.dev/',
    defaultLabel: 'frontend',
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    category: 'backend',
    logoSlug: 'nodedotjs',
    brandColor: '5FA04E',
    homepage: 'https://nodejs.org/',
    defaultLabel: 'backend',
  },
  {
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'backend',
    logoSlug: 'springboot',
    brandColor: '6DB33F',
    homepage: 'https://spring.io/projects/spring-boot',
    defaultLabel: 'backend',
  },
  {
    id: 'express',
    name: 'Express',
    category: 'backend',
    logoSlug: 'express',
    brandColor: '0A0A0A',
    homepage: 'https://expressjs.com/',
    defaultLabel: 'backend',
  },
  {
    id: 'fastapi',
    name: 'FastAPI',
    category: 'backend',
    logoSlug: 'fastapi',
    brandColor: '009688',
    homepage: 'https://fastapi.tiangolo.com/',
    defaultLabel: 'backend',
  },
  {
    id: 'ios',
    name: 'iOS',
    category: 'mobile-xr',
    logoSlug: 'ios',
    brandColor: '000000',
    homepage: 'https://developer.apple.com/ios/',
    defaultLabel: 'mobile',
  },
  {
    id: 'android',
    name: 'Android',
    category: 'mobile-xr',
    logoSlug: 'android',
    brandColor: '3DDC84',
    homepage: 'https://www.android.com/',
    defaultLabel: 'mobile',
  },
  {
    id: 'visionos',
    name: 'visionOS',
    category: 'mobile-xr',
    logoSlug: 'apple',
    brandColor: '000000',
    homepage: 'https://developer.apple.com/visionos/',
    defaultLabel: 'xr',
  },
  {
    id: 'swiftui',
    name: 'SwiftUI',
    category: 'mobile-xr',
    logoSlug: 'swift',
    brandColor: 'F05138',
    homepage: 'https://developer.apple.com/xcode/swiftui/',
    defaultLabel: 'mobile',
  },
  {
    id: 'unity',
    name: 'Unity',
    category: 'mobile-xr',
    logoSlug: 'unity',
    brandColor: 'FFFFFF',
    homepage: 'https://unity.com/',
    defaultLabel: 'xr',
  },
  {
    id: 'aws',
    name: 'AWS',
    category: 'cloud',
    logoSlug: 'amazonwebservices',
    brandColor: '232F3E',
    homepage: 'https://aws.amazon.com/',
    defaultLabel: 'cloud',
  },
  {
    id: 'docker',
    name: 'Docker',
    category: 'cloud',
    logoSlug: 'docker',
    brandColor: '2496ED',
    homepage: 'https://www.docker.com/',
    defaultLabel: 'cloud',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'cloud',
    logoSlug: 'kubernetes',
    brandColor: '326CE5',
    homepage: 'https://kubernetes.io/',
    defaultLabel: 'cloud',
  },
  {
    id: 'mysql',
    name: 'MySQL',
    category: 'database',
    logoSlug: 'mysql',
    brandColor: '4479A1',
    homepage: 'https://www.mysql.com/',
    defaultLabel: 'database',
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    logoSlug: 'postgresql',
    brandColor: '4169E1',
    homepage: 'https://www.postgresql.org/',
    defaultLabel: 'database',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'database',
    logoSlug: 'mongodb',
    brandColor: '47A248',
    homepage: 'https://www.mongodb.com/',
    defaultLabel: 'database',
  },
  {
    id: 'git',
    name: 'Git',
    category: 'tool',
    logoSlug: 'git',
    brandColor: 'F03C2E',
    homepage: 'https://git-scm.com/',
    defaultLabel: 'tool',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'tool',
    logoSlug: 'github',
    brandColor: '181717',
    homepage: 'https://github.com/',
    defaultLabel: 'tool',
  },
  {
    id: 'vscode',
    name: 'Visual Studio Code',
    category: 'tool',
    logoSlug: 'visualstudiocode',
    brandColor: '007ACC',
    homepage: 'https://code.visualstudio.com/',
    defaultLabel: 'tool',
  },
  {
    id: 'xcode',
    name: 'Xcode',
    category: 'tool',
    logoSlug: 'xcode',
    brandColor: '147EFB',
    homepage: 'https://developer.apple.com/xcode/',
    defaultLabel: 'tool',
  },
  {
    id: 'figma',
    name: 'Figma',
    category: 'tool',
    logoSlug: 'figma',
    brandColor: 'F24E1E',
    homepage: 'https://www.figma.com/',
    defaultLabel: 'tool',
  },
] as const satisfies readonly TechnologyBadgePreset[];

export const badgePalettes = [
  {
    id: 'brand',
    name: 'Brand',
    description: '회색 라벨과 기술 브랜드 색상을 사용합니다.',
    showLabel: true,
    labelColor: '555555',
    messageColor: { source: 'brand' },
    logoColor: 'white',
  },
  {
    id: 'brand-solid',
    name: 'Brand Solid',
    description: '라벨 없이 기술 브랜드 색상을 사용합니다.',
    showLabel: false,
    messageColor: { source: 'brand' },
    logoColor: 'white',
  },
  {
    id: 'dark',
    name: 'Dark',
    description: '라벨 없이 통일된 어두운 배경을 사용합니다.',
    showLabel: false,
    messageColor: { source: 'fixed', value: '24292F' },
    logoColor: 'white',
  },
] as const satisfies readonly BadgePalette[];
