import type {
  BadgeCategory,
  BadgePalette,
  TechnologyBadgePreset,
} from './badgeTypes';

// Slugs and brand colors are pinned from the Simple Icons data published at
// https://unpkg.com/simple-icons@16.27.0/data/simple-icons.json.
// Java, AWS, and Visual Studio Code were removed from current releases; their
// metadata is pinned from 4.25.0 (Java) and 12.4.0 (AWS and VS Code).
// Products without a dedicated entry intentionally reuse their platform icon:
// C# and ASP.NET Core use .NET, React Native uses React, visionOS uses Apple,
// and SwiftUI uses Swift.

export const badgeCategoryLabels = {
  language: 'Languages',
  frontend: 'Frontend',
  backend: 'Backend',
  'mobile-xr': 'Mobile & XR',
  cloud: 'Cloud & DevOps',
  database: 'Databases',
  'data-ai': 'Data & AI',
  testing: 'Testing',
  tool: 'Tools',
  project: 'Project',
} as const satisfies Record<BadgeCategory, string>;

const categoryDefaultLabels = {
  language: 'language',
  frontend: 'frontend',
  backend: 'backend',
  'mobile-xr': 'mobile',
  cloud: 'cloud',
  database: 'database',
  'data-ai': 'data / ai',
  testing: 'testing',
  tool: 'tool',
  project: 'project',
} as const satisfies Record<BadgeCategory, string>;

interface DefinedTechnologyBadgePreset extends TechnologyBadgePreset {
  defaultLabel: string;
  homepage: string;
  logoSlug: string;
}

const defineTechnologyBadgePreset = (
  id: string,
  name: string,
  category: BadgeCategory,
  logoSlug: string,
  brandColor: string,
  homepage: string,
  defaultLabel: string = categoryDefaultLabels[category],
): DefinedTechnologyBadgePreset => ({
  id,
  name,
  category,
  logoSlug,
  brandColor,
  homepage,
  defaultLabel,
});

export const technologyBadgePresets = [
  // Languages
  defineTechnologyBadgePreset('swift', 'Swift', 'language', 'swift', 'F05138', 'https://www.swift.org/'),
  defineTechnologyBadgePreset('typescript', 'TypeScript', 'language', 'typescript', '3178C6', 'https://www.typescriptlang.org/'),
  defineTechnologyBadgePreset('javascript', 'JavaScript', 'language', 'javascript', 'F7DF1E', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript/'),
  defineTechnologyBadgePreset('python', 'Python', 'language', 'python', '3776AB', 'https://www.python.org/'),
  defineTechnologyBadgePreset('java', 'Java', 'language', 'java', '007396', 'https://www.java.com/'),
  defineTechnologyBadgePreset('kotlin', 'Kotlin', 'language', 'kotlin', '7F52FF', 'https://kotlinlang.org/'),
  defineTechnologyBadgePreset('c', 'C', 'language', 'c', 'A8B9CC', 'https://www.open-std.org/jtc1/sc22/wg14/'),
  defineTechnologyBadgePreset('cpp', 'C++', 'language', 'cplusplus', '00599C', 'https://isocpp.org/'),
  defineTechnologyBadgePreset('csharp', 'C#', 'language', 'dotnet', '512BD4', 'https://learn.microsoft.com/dotnet/csharp/'),
  defineTechnologyBadgePreset('go', 'Go', 'language', 'go', '00ADD8', 'https://go.dev/'),
  defineTechnologyBadgePreset('rust', 'Rust', 'language', 'rust', '000000', 'https://www.rust-lang.org/'),
  defineTechnologyBadgePreset('php', 'PHP', 'language', 'php', '777BB4', 'https://www.php.net/'),
  defineTechnologyBadgePreset('ruby', 'Ruby', 'language', 'ruby', 'CC342D', 'https://www.ruby-lang.org/'),
  defineTechnologyBadgePreset('dart', 'Dart', 'language', 'dart', '0175C2', 'https://dart.dev/'),
  defineTechnologyBadgePreset('scala', 'Scala', 'language', 'scala', 'DC322F', 'https://www.scala-lang.org/'),
  defineTechnologyBadgePreset('r', 'R', 'language', 'r', '276DC3', 'https://www.r-project.org/'),
  defineTechnologyBadgePreset('elixir', 'Elixir', 'language', 'elixir', '4B275F', 'https://elixir-lang.org/'),
  defineTechnologyBadgePreset('lua', 'Lua', 'language', 'lua', '000080', 'https://www.lua.org/'),
  defineTechnologyBadgePreset('gnu-bash', 'GNU Bash', 'language', 'gnubash', '4EAA25', 'https://www.gnu.org/software/bash/'),
  defineTechnologyBadgePreset('solidity', 'Solidity', 'language', 'solidity', '363636', 'https://soliditylang.org/'),

  // Frontend and desktop UI
  defineTechnologyBadgePreset('react', 'React', 'frontend', 'react', '61DAFB', 'https://react.dev/'),
  defineTechnologyBadgePreset('vue', 'Vue.js', 'frontend', 'vuedotjs', '4FC08D', 'https://vuejs.org/'),
  defineTechnologyBadgePreset('angular', 'Angular', 'frontend', 'angular', '0F0F11', 'https://angular.dev/'),
  defineTechnologyBadgePreset('svelte', 'Svelte', 'frontend', 'svelte', 'FF3E00', 'https://svelte.dev/'),
  defineTechnologyBadgePreset('nextjs', 'Next.js', 'frontend', 'nextdotjs', '000000', 'https://nextjs.org/'),
  defineTechnologyBadgePreset('nuxt', 'Nuxt', 'frontend', 'nuxt', '00DC82', 'https://nuxt.com/'),
  defineTechnologyBadgePreset('astro', 'Astro', 'frontend', 'astro', 'BC52EE', 'https://astro.build/'),
  defineTechnologyBadgePreset('remix', 'Remix', 'frontend', 'remix', '000000', 'https://remix.run/'),
  defineTechnologyBadgePreset('gatsby', 'Gatsby', 'frontend', 'gatsby', '663399', 'https://www.gatsbyjs.com/'),
  defineTechnologyBadgePreset('solidjs', 'SolidJS', 'frontend', 'solid', '2C4F7C', 'https://www.solidjs.com/'),
  defineTechnologyBadgePreset('qwik', 'Qwik', 'frontend', 'qwik', 'AC7EF4', 'https://qwik.dev/'),
  defineTechnologyBadgePreset('html5', 'HTML5', 'frontend', 'html5', 'E34F26', 'https://html.spec.whatwg.org/'),
  defineTechnologyBadgePreset('css3', 'CSS3', 'frontend', 'css', '663399', 'https://www.w3.org/Style/CSS/'),
  defineTechnologyBadgePreset('bootstrap', 'Bootstrap', 'frontend', 'bootstrap', '7952B3', 'https://getbootstrap.com/'),
  defineTechnologyBadgePreset('tailwind-css', 'Tailwind CSS', 'frontend', 'tailwindcss', '06B6D4', 'https://tailwindcss.com/'),
  defineTechnologyBadgePreset('sass', 'Sass', 'frontend', 'sass', 'CC6699', 'https://sass-lang.com/'),
  defineTechnologyBadgePreset('less', 'Less', 'frontend', 'less', '1D365D', 'https://lesscss.org/'),
  defineTechnologyBadgePreset('htmx', 'htmx', 'frontend', 'htmx', '3366CC', 'https://htmx.org/'),
  defineTechnologyBadgePreset('jquery', 'jQuery', 'frontend', 'jquery', '0769AD', 'https://jquery.com/'),
  defineTechnologyBadgePreset('vite', 'Vite', 'frontend', 'vite', '9135FF', 'https://vite.dev/'),
  defineTechnologyBadgePreset('webpack', 'Webpack', 'frontend', 'webpack', '8DD6F9', 'https://webpack.js.org/'),
  defineTechnologyBadgePreset('rollup', 'Rollup.js', 'frontend', 'rollupdotjs', 'EC4A3F', 'https://rollupjs.org/'),
  defineTechnologyBadgePreset('electron', 'Electron', 'frontend', 'electron', '47848F', 'https://www.electronjs.org/'),
  defineTechnologyBadgePreset('tauri', 'Tauri', 'frontend', 'tauri', '24C8D8', 'https://tauri.app/'),

  // Backend
  defineTechnologyBadgePreset('nodejs', 'Node.js', 'backend', 'nodedotjs', '5FA04E', 'https://nodejs.org/'),
  defineTechnologyBadgePreset('spring-boot', 'Spring Boot', 'backend', 'springboot', '6DB33F', 'https://spring.io/projects/spring-boot'),
  defineTechnologyBadgePreset('express', 'Express', 'backend', 'express', '0A0A0A', 'https://expressjs.com/'),
  defineTechnologyBadgePreset('fastapi', 'FastAPI', 'backend', 'fastapi', '009688', 'https://fastapi.tiangolo.com/'),
  defineTechnologyBadgePreset('nestjs', 'NestJS', 'backend', 'nestjs', 'E0234E', 'https://nestjs.com/'),
  defineTechnologyBadgePreset('django', 'Django', 'backend', 'django', '092E20', 'https://www.djangoproject.com/'),
  defineTechnologyBadgePreset('flask', 'Flask', 'backend', 'flask', '3BABC3', 'https://flask.palletsprojects.com/'),
  defineTechnologyBadgePreset('ruby-on-rails', 'Ruby on Rails', 'backend', 'rubyonrails', 'D30001', 'https://rubyonrails.org/'),
  defineTechnologyBadgePreset('laravel', 'Laravel', 'backend', 'laravel', 'FF2D20', 'https://laravel.com/'),
  defineTechnologyBadgePreset('symfony', 'Symfony', 'backend', 'symfony', '000000', 'https://symfony.com/'),
  defineTechnologyBadgePreset('aspnet-core', 'ASP.NET Core', 'backend', 'dotnet', '512BD4', 'https://dotnet.microsoft.com/apps/aspnet'),
  defineTechnologyBadgePreset('phoenix', 'Phoenix Framework', 'backend', 'phoenixframework', 'FD4F00', 'https://www.phoenixframework.org/'),
  defineTechnologyBadgePreset('deno', 'Deno', 'backend', 'deno', '000000', 'https://deno.com/'),
  defineTechnologyBadgePreset('bun', 'Bun', 'backend', 'bun', '000000', 'https://bun.sh/'),
  defineTechnologyBadgePreset('graphql', 'GraphQL', 'backend', 'graphql', 'E10098', 'https://graphql.org/'),
  defineTechnologyBadgePreset('apollo-graphql', 'Apollo GraphQL', 'backend', 'apollographql', '311C87', 'https://www.apollographql.com/'),
  defineTechnologyBadgePreset('prisma', 'Prisma', 'backend', 'prisma', '2D3748', 'https://www.prisma.io/'),
  defineTechnologyBadgePreset('nginx', 'NGINX', 'backend', 'nginx', '009639', 'https://nginx.org/'),

  // Mobile and XR
  defineTechnologyBadgePreset('ios', 'iOS', 'mobile-xr', 'ios', '000000', 'https://developer.apple.com/ios/'),
  defineTechnologyBadgePreset('android', 'Android', 'mobile-xr', 'android', '3DDC84', 'https://www.android.com/'),
  defineTechnologyBadgePreset('visionos', 'visionOS', 'mobile-xr', 'apple', '000000', 'https://developer.apple.com/visionos/', 'xr'),
  defineTechnologyBadgePreset('swiftui', 'SwiftUI', 'mobile-xr', 'swift', 'F05138', 'https://developer.apple.com/xcode/swiftui/'),
  defineTechnologyBadgePreset('flutter', 'Flutter', 'mobile-xr', 'flutter', '02569B', 'https://flutter.dev/'),
  defineTechnologyBadgePreset('react-native', 'React Native', 'mobile-xr', 'react', '61DAFB', 'https://reactnative.dev/'),
  defineTechnologyBadgePreset('expo', 'Expo', 'mobile-xr', 'expo', '1C2024', 'https://expo.dev/'),
  defineTechnologyBadgePreset('ionic', 'Ionic', 'mobile-xr', 'ionic', '3880FF', 'https://ionicframework.com/'),
  defineTechnologyBadgePreset('unity', 'Unity', 'mobile-xr', 'unity', 'FFFFFF', 'https://unity.com/', 'xr'),
  defineTechnologyBadgePreset('unreal-engine', 'Unreal Engine', 'mobile-xr', 'unrealengine', '0E1128', 'https://www.unrealengine.com/', 'xr'),
  defineTechnologyBadgePreset('godot-engine', 'Godot Engine', 'mobile-xr', 'godotengine', '478CBF', 'https://godotengine.org/'),

  // Cloud and DevOps
  defineTechnologyBadgePreset('aws', 'AWS', 'cloud', 'amazonwebservices', '232F3E', 'https://aws.amazon.com/'),
  defineTechnologyBadgePreset('google-cloud', 'Google Cloud', 'cloud', 'googlecloud', '4285F4', 'https://cloud.google.com/'),
  defineTechnologyBadgePreset('cloudflare', 'Cloudflare', 'cloud', 'cloudflare', 'F38020', 'https://www.cloudflare.com/'),
  defineTechnologyBadgePreset('vercel', 'Vercel', 'cloud', 'vercel', '000000', 'https://vercel.com/'),
  defineTechnologyBadgePreset('netlify', 'Netlify', 'cloud', 'netlify', '00C7B7', 'https://www.netlify.com/'),
  defineTechnologyBadgePreset('firebase', 'Firebase', 'cloud', 'firebase', 'DD2C00', 'https://firebase.google.com/'),
  defineTechnologyBadgePreset('digitalocean', 'DigitalOcean', 'cloud', 'digitalocean', '0080FF', 'https://www.digitalocean.com/'),
  defineTechnologyBadgePreset('docker', 'Docker', 'cloud', 'docker', '2496ED', 'https://www.docker.com/'),
  defineTechnologyBadgePreset('kubernetes', 'Kubernetes', 'cloud', 'kubernetes', '326CE5', 'https://kubernetes.io/'),
  defineTechnologyBadgePreset('terraform', 'Terraform', 'cloud', 'terraform', '844FBA', 'https://www.terraform.io/'),
  defineTechnologyBadgePreset('opentofu', 'OpenTofu', 'cloud', 'opentofu', 'FFDA18', 'https://opentofu.org/'),
  defineTechnologyBadgePreset('pulumi', 'Pulumi', 'cloud', 'pulumi', '8A3391', 'https://www.pulumi.com/'),
  defineTechnologyBadgePreset('ansible', 'Ansible', 'cloud', 'ansible', 'EE0000', 'https://www.ansible.com/'),
  defineTechnologyBadgePreset('jenkins', 'Jenkins', 'cloud', 'jenkins', 'D24939', 'https://www.jenkins.io/'),
  defineTechnologyBadgePreset('github-actions', 'GitHub Actions', 'cloud', 'githubactions', '2088FF', 'https://github.com/features/actions'),
  defineTechnologyBadgePreset('gitlab-ci', 'GitLab CI/CD', 'cloud', 'gitlab', 'FC6D26', 'https://docs.gitlab.com/ci/'),
  defineTechnologyBadgePreset('circleci', 'CircleCI', 'cloud', 'circleci', '343434', 'https://circleci.com/'),
  defineTechnologyBadgePreset('travis-ci', 'Travis CI', 'cloud', 'travisci', '3EAAAF', 'https://www.travis-ci.com/'),
  defineTechnologyBadgePreset('argo-cd', 'Argo CD', 'cloud', 'argo', 'EF7B4D', 'https://argo-cd.readthedocs.io/'),
  defineTechnologyBadgePreset('helm', 'Helm', 'cloud', 'helm', '0F1689', 'https://helm.sh/'),
  defineTechnologyBadgePreset('prometheus', 'Prometheus', 'cloud', 'prometheus', 'E6522C', 'https://prometheus.io/'),
  defineTechnologyBadgePreset('grafana', 'Grafana', 'cloud', 'grafana', 'F46800', 'https://grafana.com/'),
  defineTechnologyBadgePreset('datadog', 'Datadog', 'cloud', 'datadog', '632CA6', 'https://www.datadoghq.com/'),

  // Databases and search
  defineTechnologyBadgePreset('mysql', 'MySQL', 'database', 'mysql', '4479A1', 'https://www.mysql.com/'),
  defineTechnologyBadgePreset('postgresql', 'PostgreSQL', 'database', 'postgresql', '4169E1', 'https://www.postgresql.org/'),
  defineTechnologyBadgePreset('mongodb', 'MongoDB', 'database', 'mongodb', '47A248', 'https://www.mongodb.com/'),
  defineTechnologyBadgePreset('sqlite', 'SQLite', 'database', 'sqlite', '003B57', 'https://www.sqlite.org/'),
  defineTechnologyBadgePreset('redis', 'Redis', 'database', 'redis', 'FF4438', 'https://redis.io/'),
  defineTechnologyBadgePreset('mariadb', 'MariaDB', 'database', 'mariadb', '003545', 'https://mariadb.org/'),
  defineTechnologyBadgePreset('apache-cassandra', 'Apache Cassandra', 'database', 'apachecassandra', '1287B1', 'https://cassandra.apache.org/'),
  defineTechnologyBadgePreset('cockroachdb', 'CockroachDB', 'database', 'cockroachlabs', '6933FF', 'https://www.cockroachlabs.com/'),
  defineTechnologyBadgePreset('neo4j', 'Neo4j', 'database', 'neo4j', '4581C3', 'https://neo4j.com/'),
  defineTechnologyBadgePreset('supabase', 'Supabase', 'database', 'supabase', '3FCF8E', 'https://supabase.com/'),
  defineTechnologyBadgePreset('planetscale', 'PlanetScale', 'database', 'planetscale', '000000', 'https://planetscale.com/'),
  defineTechnologyBadgePreset('elasticsearch', 'Elasticsearch', 'database', 'elasticsearch', '005571', 'https://www.elastic.co/elasticsearch'),
  defineTechnologyBadgePreset('influxdb', 'InfluxDB', 'database', 'influxdb', '22ADF6', 'https://www.influxdata.com/'),
  defineTechnologyBadgePreset('snowflake', 'Snowflake', 'database', 'snowflake', '29B5E8', 'https://www.snowflake.com/'),
  defineTechnologyBadgePreset('clickhouse', 'ClickHouse', 'database', 'clickhouse', 'FFCC01', 'https://clickhouse.com/'),

  // Data and AI
  defineTechnologyBadgePreset('tensorflow', 'TensorFlow', 'data-ai', 'tensorflow', 'FF6F00', 'https://www.tensorflow.org/'),
  defineTechnologyBadgePreset('pytorch', 'PyTorch', 'data-ai', 'pytorch', 'EE4C2C', 'https://pytorch.org/'),
  defineTechnologyBadgePreset('keras', 'Keras', 'data-ai', 'keras', 'D00000', 'https://keras.io/'),
  defineTechnologyBadgePreset('scikit-learn', 'scikit-learn', 'data-ai', 'scikitlearn', 'F7931E', 'https://scikit-learn.org/'),
  defineTechnologyBadgePreset('pandas', 'pandas', 'data-ai', 'pandas', '150458', 'https://pandas.pydata.org/'),
  defineTechnologyBadgePreset('numpy', 'NumPy', 'data-ai', 'numpy', '013243', 'https://numpy.org/'),
  defineTechnologyBadgePreset('jupyter', 'Jupyter', 'data-ai', 'jupyter', 'F37626', 'https://jupyter.org/'),
  defineTechnologyBadgePreset('hugging-face', 'Hugging Face', 'data-ai', 'huggingface', 'FFD21E', 'https://huggingface.co/'),
  defineTechnologyBadgePreset('apache-spark', 'Apache Spark', 'data-ai', 'apachespark', 'E25A1C', 'https://spark.apache.org/'),
  defineTechnologyBadgePreset('apache-kafka', 'Apache Kafka', 'data-ai', 'apachekafka', '231F20', 'https://kafka.apache.org/'),
  defineTechnologyBadgePreset('databricks', 'Databricks', 'data-ai', 'databricks', 'FF3621', 'https://www.databricks.com/'),
  defineTechnologyBadgePreset('mlflow', 'MLflow', 'data-ai', 'mlflow', '0194E2', 'https://mlflow.org/'),
  defineTechnologyBadgePreset('langchain', 'LangChain', 'data-ai', 'langchain', '7FC8FF', 'https://www.langchain.com/'),
  defineTechnologyBadgePreset('ollama', 'Ollama', 'data-ai', 'ollama', '000000', 'https://ollama.com/'),

  // Testing
  defineTechnologyBadgePreset('vitest', 'Vitest', 'testing', 'vitest', '00FF74', 'https://vitest.dev/'),
  defineTechnologyBadgePreset('jest', 'Jest', 'testing', 'jest', 'C21325', 'https://jestjs.io/'),
  defineTechnologyBadgePreset('cypress', 'Cypress', 'testing', 'cypress', '69D3A7', 'https://www.cypress.io/'),
  defineTechnologyBadgePreset('selenium', 'Selenium', 'testing', 'selenium', '43B02A', 'https://www.selenium.dev/'),
  defineTechnologyBadgePreset('testing-library', 'Testing Library', 'testing', 'testinglibrary', 'E33332', 'https://testing-library.com/'),
  defineTechnologyBadgePreset('mocha', 'Mocha', 'testing', 'mocha', '8D6748', 'https://mochajs.org/'),
  defineTechnologyBadgePreset('jasmine', 'Jasmine', 'testing', 'jasmine', '8A4182', 'https://jasmine.github.io/'),
  defineTechnologyBadgePreset('junit5', 'JUnit 5', 'testing', 'junit5', '25A162', 'https://junit.org/junit5/'),
  defineTechnologyBadgePreset('cucumber', 'Cucumber', 'testing', 'cucumber', '23D96C', 'https://cucumber.io/'),
  defineTechnologyBadgePreset('storybook', 'Storybook', 'testing', 'storybook', 'FF4785', 'https://storybook.js.org/'),

  // Tools and platforms
  defineTechnologyBadgePreset('git', 'Git', 'tool', 'git', 'F03C2E', 'https://git-scm.com/'),
  defineTechnologyBadgePreset('github', 'GitHub', 'tool', 'github', '181717', 'https://github.com/'),
  defineTechnologyBadgePreset('gitlab', 'GitLab', 'tool', 'gitlab', 'FC6D26', 'https://gitlab.com/'),
  defineTechnologyBadgePreset('bitbucket', 'Bitbucket', 'tool', 'bitbucket', '0052CC', 'https://bitbucket.org/'),
  defineTechnologyBadgePreset('vscode', 'Visual Studio Code', 'tool', 'visualstudiocode', '007ACC', 'https://code.visualstudio.com/'),
  defineTechnologyBadgePreset('vscodium', 'VSCodium', 'tool', 'vscodium', '2F80ED', 'https://vscodium.com/'),
  defineTechnologyBadgePreset('cursor', 'Cursor', 'tool', 'cursor', '000000', 'https://cursor.com/'),
  defineTechnologyBadgePreset('xcode', 'Xcode', 'tool', 'xcode', '147EFB', 'https://developer.apple.com/xcode/'),
  defineTechnologyBadgePreset('android-studio', 'Android Studio', 'tool', 'androidstudio', '3DDC84', 'https://developer.android.com/studio'),
  defineTechnologyBadgePreset('intellij-idea', 'IntelliJ IDEA', 'tool', 'intellijidea', '000000', 'https://www.jetbrains.com/idea/'),
  defineTechnologyBadgePreset('vim', 'Vim', 'tool', 'vim', '019733', 'https://www.vim.org/'),
  defineTechnologyBadgePreset('neovim', 'Neovim', 'tool', 'neovim', '57A143', 'https://neovim.io/'),
  defineTechnologyBadgePreset('npm', 'npm', 'tool', 'npm', 'CB3837', 'https://www.npmjs.com/'),
  defineTechnologyBadgePreset('pnpm', 'pnpm', 'tool', 'pnpm', 'F69220', 'https://pnpm.io/'),
  defineTechnologyBadgePreset('yarn', 'Yarn', 'tool', 'yarn', '2C8EBB', 'https://yarnpkg.com/'),
  defineTechnologyBadgePreset('homebrew', 'Homebrew', 'tool', 'homebrew', 'FBB040', 'https://brew.sh/'),
  defineTechnologyBadgePreset('gradle', 'Gradle', 'tool', 'gradle', '02303A', 'https://gradle.org/'),
  defineTechnologyBadgePreset('maven', 'Apache Maven', 'tool', 'apachemaven', 'C71A36', 'https://maven.apache.org/'),
  defineTechnologyBadgePreset('eslint', 'ESLint', 'tool', 'eslint', '4B32C3', 'https://eslint.org/'),
  defineTechnologyBadgePreset('prettier', 'Prettier', 'tool', 'prettier', 'F7B93E', 'https://prettier.io/'),
  defineTechnologyBadgePreset('figma', 'Figma', 'tool', 'figma', 'F24E1E', 'https://www.figma.com/'),
  defineTechnologyBadgePreset('jira', 'Jira', 'tool', 'jira', '0052CC', 'https://www.atlassian.com/software/jira'),
  defineTechnologyBadgePreset('notion', 'Notion', 'tool', 'notion', '000000', 'https://www.notion.so/'),
  defineTechnologyBadgePreset('postman', 'Postman', 'tool', 'postman', 'FF6C37', 'https://www.postman.com/'),
  defineTechnologyBadgePreset('insomnia', 'Insomnia', 'tool', 'insomnia', '4000BF', 'https://insomnia.rest/'),
  defineTechnologyBadgePreset('swagger', 'Swagger', 'tool', 'swagger', '85EA2D', 'https://swagger.io/'),
  defineTechnologyBadgePreset('linux', 'Linux', 'tool', 'linux', 'FCC624', 'https://www.linux.org/'),
  defineTechnologyBadgePreset('macos', 'macOS', 'tool', 'macos', '000000', 'https://www.apple.com/macos/'),
  defineTechnologyBadgePreset('ubuntu', 'Ubuntu', 'tool', 'ubuntu', 'E95420', 'https://ubuntu.com/'),
] as const satisfies readonly TechnologyBadgePreset[];

export const badgePalettes = [
  {
    id: 'brand',
    name: 'Brand',
    description: "Uses the technology's brand color.",
    labelColor: '555555',
    messageColor: { source: 'brand' },
    logoColor: 'white',
  },
  {
    id: 'dark',
    name: 'Dark',
    description: 'Uses a consistent dark background.',
    labelColor: '555555',
    messageColor: { source: 'fixed', value: '24292F' },
    logoColor: 'white',
  },
] as const satisfies readonly BadgePalette[];
